#!/bin/sh

set -e

if [ "`uname -s`" = "Darwin" ]; then
  if ! script/checksum check-brew; then
    brew bundle check >&/dev/null || {
      echo "Updating Homebrew dependences"
      brew update >/dev/null
      brew bundle
    }

    echo "Ensuring that ruby is installed"
    brew bootstrap-rbenv-ruby

    script/checksum record-brew
  fi
fi

if ! script/checksum check-gems; then
  bundle --path .bundle
  script/checksum record-gems
fi

if ! script/checksum check-npm; then
  npm install
  script/checksum record-npm
fi
